// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDQVXbt12NnR_n1MWZ6edvVacx6w8X6AU',
    appId: '1:473602958624:web:1ef3d518ce5c6ea6a1a345',
    messagingSenderId: '473602958624',
    projectId: 'airbnb-07',
    authDomain: 'airbnb-07.firebaseapp.com',
    storageBucket: 'airbnb-07.firebasestorage.app',
    measurementId: 'G-EER9WWT80Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbHV2x16nUVI3Fn50bUtug951Vi8yvJsg',
    appId: '1:473602958624:android:645ea11101d032a2a1a345',
    messagingSenderId: '473602958624',
    projectId: 'airbnb-07',
    storageBucket: 'airbnb-07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHs3EPbZLHRahVYZMHAIMXyZ5JquCNSBQ',
    appId: '1:473602958624:ios:5f671644f45c711ba1a345',
    messagingSenderId: '473602958624',
    projectId: 'airbnb-07',
    storageBucket: 'airbnb-07.firebasestorage.app',
    iosBundleId: 'com.example.wanderin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHs3EPbZLHRahVYZMHAIMXyZ5JquCNSBQ',
    appId: '1:473602958624:ios:5f671644f45c711ba1a345',
    messagingSenderId: '473602958624',
    projectId: 'airbnb-07',
    storageBucket: 'airbnb-07.firebasestorage.app',
    iosBundleId: 'com.example.wanderin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDQVXbt12NnR_n1MWZ6edvVacx6w8X6AU',
    appId: '1:473602958624:web:5c1a3c7ea9ef91d0a1a345',
    messagingSenderId: '473602958624',
    projectId: 'airbnb-07',
    authDomain: 'airbnb-07.firebaseapp.com',
    storageBucket: 'airbnb-07.firebasestorage.app',
    measurementId: 'G-DXY8DK70NX',
  );

}